interface ReportData {
  generatedDate: string;
  organizationName: string;
  assessmentPeriod: string;
  totalInteractions: number;
  avgResponseTime: string;
  complianceScore: string;
  interactions: Array<{
    timestamp: string;
    userMessage: string;
    aiResponse: string;
  }>;
  findings: Array<{
    title: string;
    description: string;
    riskLevel: string;
  }>;
  transparencyRisk: string;
  transparencyStatus: string;
  dataProtectionRisk: string;
  dataProtectionStatus: string;
  biasRisk: string;
  biasStatus: string;
  reportId: string;
  upgradeUrl: string;
}

export function generateReportHtml (data: ReportData): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>EU AI Act Compliance Report</title>
  <style>
    body {
      font-family: system-ui, -apple-system, sans-serif;
      line-height: 1.5;
      margin: 0;
      padding: 2rem;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 1rem 0;
    }
    th, td {
      padding: 0.5rem;
      border: 1px solid #e2e8f0;
      text-align: left;
    }
    th {
      background-color: #f8fafc;
    }
    .metadata {
      margin: 2rem 0;
    }
    .interaction {
      margin: 1rem 0;
      padding: 1rem;
      background-color: #f8fafc;
      border-radius: 0.5rem;
    }
    .findings li {
      margin: 1rem 0;
    }
    footer {
      margin-top: 4rem;
      padding-top: 2rem;
      border-top: 1px solid #e2e8f0;
      font-size: 0.875rem;
      color: #64748b;
    }
  </style>
</head>
<body>
  <header>
    <h1>EU AI Act Compliance Report</h1>
    <div class="metadata">
      <table>
        <tr>
          <th>Report Generated:</th>
          <td>${data.generatedDate}</td>
        </tr>
        <tr>
          <th>Organization:</th>
          <td>${data.organizationName}</td>
        </tr>
        <tr>
          <th>Assessment Period:</th>
          <td>${data.assessmentPeriod}</td>
        </tr>
      </table>
    </div>
  </header>

  <main>
    <section>
      <h2>Conversation Metadata</h2>
      <table>
        <tr>
          <th>Total Interactions:</th>
          <td>${data.totalInteractions}</td>
        </tr>
        <tr>
          <th>Average Response Time:</th>
          <td>${data.avgResponseTime}</td>
        </tr>
        <tr>
          <th>Compliance Score:</th>
          <td>${data.complianceScore}</td>
        </tr>
      </table>
    </section>

    <section>
      <h2>Partial Conversation Transcript</h2>
      <h3>First 5 Interactions</h3>
      <div class="conversation">
        ${data.interactions.map(interaction => `
          <div class="interaction">
            <p><strong>User (${interaction.timestamp}):</strong> ${interaction.userMessage}</p>
            <p><strong>AI:</strong> ${interaction.aiResponse}</p>
          </div>
        `).join('')}
      </div>
    </section>

    <section>
      <h2>Top 3 Compliance Findings</h2>
      <ol class="findings">
        ${data.findings.map(finding => `
          <li>
            <h3>${finding.title}</h3>
            <p>${finding.description}</p>
            <p><strong>Risk Level:</strong> ${finding.riskLevel}</p>
          </li>
        `).join('')}
      </ol>
    </section>

    <section>
      <h2>Basic Risk Assessment</h2>
      <table>
        <thead>
          <tr>
            <th>Risk Category</th>
            <th>Risk Level</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Transparency</td>
            <td>${data.transparencyRisk}</td>
            <td>${data.transparencyStatus}</td>
          </tr>
          <tr>
            <td>Data Protection</td>
            <td>${data.dataProtectionRisk}</td>
            <td>${data.dataProtectionStatus}</td>
          </tr>
          <tr>
            <td>Bias & Fairness</td>
            <td>${data.biasRisk}</td>
            <td>${data.biasStatus}</td>
          </tr>
        </tbody>
      </table>
    </section>

    <section class="cta">
      <h2>Upgrade to Premium</h2>
      <p>Get access to:</p>
      <ul>
        <li>Full compliance audit</li>
        <li>Detailed metrics and analytics</li>
        <li>Personalized recommendations</li>
        <li>Expert consultation</li>
      </ul>
      <div class="upgrade-button">
        <a href="${data.upgradeUrl}">Upgrade to Premium</a>
      </div>
    </section>
  </main>

  <footer>
    <p>Generated by Rizk Compliance Platform</p>
    <p>Report ID: ${data.reportId}</p>
  </footer>
</body>
</html>`;
} 